title: Graphic Design by Jalal
author: Jalal
email: jalalabdulaziz@gmail.com
description: Graphic design works by Jalal.

twitter_username: jalalabdulaziz
github_username:  jalalabdul

google_analytics: UA-101729051-1

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock