title: Jalal Abdul Aziz
author: Jalal
email: jalalabdulaziz@gmail.com
description: Graphic design works by Jalal.

twitter_username: jalalabdulaziz
github_username:  jalalabdul

google_analytics: UA-101729051-1

markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock