title: Jalal
author: Jalal
email: jalalabdulaziz@gmail.com
description: Jalal is a graphic designer working and living in Bali.
environment: production
baseurl: ""
url: "https://jalal.id"
permalink: /projects/:title
google_analytics: UA-101729051-1
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock